import { promises as fs } from 'node:fs'
import path from 'node:path'

// Writes a breadcrumb trail of free-API interactions into the user's chosen
// repo folder, so Claude — working in that same folder — can see the context of
// the lighter coding tasks handled here. Two files are kept under
// <folder>/llm-context:
//   - history.jsonl : append-only durable log (one JSON object per line)
//   - HISTORY.md    : the most recent N interactions, human/Claude readable

export interface Interaction {
  time: string
  provider: string | null
  model: string | null
  tier: string | null
  prompt: string
  reply: string
}

const SUBDIR = 'llm-context'

const contextPaths = (folder: string) => {
  const dir = path.join(folder, SUBDIR)
  return {
    dir,
    jsonl: path.join(dir, 'history.jsonl'),
    markdown: path.join(dir, 'HISTORY.md'),
  }
}

const readRecent = async (jsonl: string, limit: number): Promise<Interaction[]> => {
  let raw = ''
  try {
    raw = await fs.readFile(jsonl, 'utf8')
  } catch {
    return []
  }
  const lines = raw.split('\n').filter((l) => l.trim().length > 0)
  const recent = lines.slice(-limit)
  const out: Interaction[] = []
  for (const line of recent) {
    try {
      out.push(JSON.parse(line) as Interaction)
    } catch {
      // skip a corrupt line
    }
  }
  return out
}

const renderMarkdown = (entries: Interaction[]): string => {
  const header =
    '# Free-LLM API — recent interactions\n\n' +
    '_Auto-generated by free-llm-api. These are prompts handled by the free API ' +
    '(lighter coding tasks) so Claude can pick up their context. Most recent first._\n\n'
  const blocks = [...entries]
    .reverse()
    .map((e) => {
      const model = [e.provider, e.model].filter(Boolean).join(' · ') || 'unknown'
      const tier = e.tier ? ` · ${e.tier}` : ''
      const prompt = e.prompt.trim().split('\n').map((l) => `> ${l}`).join('\n')
      return (
        `## ${e.time} · ${model}${tier}\n\n` +
        `**Prompt**\n\n${prompt}\n\n` +
        `**Reply**\n\n${e.reply.trim() || '_(streamed / not captured)_'}\n`
      )
    })
    .join('\n---\n\n')
  return header + blocks + '\n'
}

// Best-effort append; never throws into the request path.
export const appendInteraction = async (
  folder: string,
  entry: Interaction,
  maxEntries: number,
): Promise<void> => {
  const { dir, jsonl, markdown } = contextPaths(folder)
  await fs.mkdir(dir, { recursive: true })
  await fs.appendFile(jsonl, JSON.stringify(entry) + '\n', 'utf8')
  const recent = await readRecent(jsonl, maxEntries)
  await fs.writeFile(markdown, renderMarkdown(recent), 'utf8')
}
